// src/components/ssh/ServerOverviewPanel.vue
<script setup lang="ts">
import { useServerOverviewPolling } from "@/composables/useServerOverviewPolling";

useServerOverviewPolling();

const { selectSession } = toRefs(useChannelInstancesStore());

const overview = computed(() => selectSession.value?.overview);
</script>

<template>
    <div class="overview-root">
        <template v-if="selectSession && overview">
            <div v-if="overview.error" class="ov-err">{{ overview.error }}</div>
            <ServerMessage />
            <ServerResource />
            <div class="disk-scroll-region">
                <ServerDisk />
            </div>
        </template>
        <div v-else class="empty">暂无连接的服务器</div>
    </div>
</template>

<style scoped lang="scss">
.overview-root {
    flex: 1;
    min-height: 0;
    height: 100%;
    padding: 6px 0 10px;
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.disk-scroll-region {
    flex: 1 1 0;
    min-height: 0;
    overflow-x: hidden;
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
    border-radius: 8px;
}

.ov-err {
    padding: 8px 10px;
    font-size: var(--font-size-xs);
    border-radius: 8px;
}

.empty {
    padding: 24px 12px;
    text-align: center;
    border-radius: 8px;
}
</style>

// web-next/src/components/ssh/ServerOverviewPanel/index.tsx
"use client";

import { useServerOverviewPolling } from "@/hooks/useServerOverviewPolling";
import { useChannelInstancesStore, isChannelInstance } from "@/stores/channelInstances";
import ServerDisk from "@/components/ssh/ServerDisk";
import ServerMessage from "@/components/ssh/ServerMessage";
import ServerResource from "@/components/ssh/ServerResource";
import "./index.scss";

export default function ServerOverviewPanel() {
    useServerOverviewPolling();
    const selectSession = useChannelInstancesStore((state) => state.selectSession);
    const instance = selectSession && isChannelInstance(selectSession) ? selectSession : null;
    const overview = instance?.overview;

    return (
        <div className="ServerOverviewPanel overview-root">
            {instance && overview ? (
                <>
                    {overview.error ? <div className="ov-err">{overview.error}</div> : null}
                    <ServerMessage />
                    <ServerResource />
                    <div className="disk-scroll-region">
                        <ServerDisk />
                    </div>
                </>
            ) : (
                <div className="empty">暂无连接的服务器</div>
            )}
        </div>
    );
}
