// src/components/window/SettingWin.vue
<script setup lang="ts">
import type { SettingsTab } from "@/components/SettingDialog.vue";

const activeTab = ref<SettingsTab>("general");
onMounted(() => {
    document.body.classList.add("setting-window");
    const params = new URLSearchParams(location.search);
    activeTab.value = (params.get("tab") as SettingsTab) || "general";
});
</script>

<template>
    <SettingDialog v-model:activeTab="activeTab" />
</template>

// web-next/src/components/window/SettingWin/index.tsx
"use client";

import { useEffect, useState } from "react";
import SettingDialog from "@/components/SettingDialog";
import type { SettingsTab } from "@/types/settings";
import "./index.scss";

export default function SettingWin() {
    const [activeTab, setActiveTab] = useState<SettingsTab>("general");

    useEffect(() => {
        document.body.classList.add("setting-window");
        const params = new URLSearchParams(location.search);
        setActiveTab((params.get("tab") as SettingsTab) || "general");
        return () => document.body.classList.remove("setting-window");
    }, []);

    return (
        <main className="SettingWin">
            <SettingDialog activeTab={activeTab} onActiveTabChange={setActiveTab} />
        </main>
    );
}
