// web-next/src/components/sftp/SftpTransferItem/index.tsx
"use client";

import { useState } from "react";
import { openPath, revealItemInDir } from "@tauri-apps/plugin-opener";
import Icon from "@/components/Icon";
import type { MenuItem } from "@/components/DefaultMenuItems";
import type { TransferItem, TransferStatus } from "@/stores/downloadStore";
import { countdownText } from "@/utils";
import { CustomMenusEventKey } from "@/utils/constant";
import { removeLocalIfAny } from "@/utils/localFsUtils";
import { formatAdaptiveBytes, formatSpeedBps } from "@/utils/project";
import { showToast } from "@/utils/ui";
import "./index.scss";

export type SftpTransferItemProps = {
    item: TransferItem;
    level?: number;
};

function statusText(status: TransferStatus): string {
    if (status === "running") return "进行中";
    if (status === "queued") return "排队";
    if (status === "paused") return "已暂停";
    if (status === "cancelled") return "已取消";
    if (status === "success") return "完成";
    return "失败";
}

export default function SftpTransferItem({ item, level = 0 }: SftpTransferItemProps) {
    const [open, setOpen] = useState(true);
    const [renderChildren, setRenderChildren] = useState(true);
    const [childrenClosing, setChildrenClosing] = useState(false);
    const canPause = item.status === "running" || item.status === "queued";
    const canResume = item.status === "paused";
    const canCancel = ["running", "queued", "paused", "error"].includes(item.status);
    const canRetry = item.status === "error";
    const percent = ((item.loaded / (item.total || 1)) * 100).toFixed(2);

    async function handleOpenFile() {
        if (!item.localPath || item.isDir) return;
        try {
            await openPath(item.localPath);
        } catch (error) {
            console.error(error);
            showToast(error instanceof Error ? error.message : "打开文件失败", "error");
        }
    }

    async function handleRevealInDir() {
        if (!item.localPath) return;
        try {
            await revealItemInDir(item.localPath);
        } catch (error) {
            showToast(error instanceof Error ? error.message : "打开所在位置失败", "error");
        }
    }

    function openContextMenu(event: React.MouseEvent) {
        event.preventDefault();
        event.stopPropagation();
        const menus: MenuItem[] = [
            { label: "打开", disabled: item.isDir, handler: () => void handleOpenFile() },
            { label: "打开所在位置", handler: () => void handleRevealInDir() },
            "---",
            {
                label: "取消并删除本地",
                handler: () => {
                    void item.cancel();
                    void removeLocalIfAny(item.localPath);
                },
            },
        ];
        document.body.dispatchEvent(new CustomEvent(CustomMenusEventKey, { bubbles: true, detail: { menus, target: event.nativeEvent } }));
    }

    function toggleChildren(event: React.MouseEvent) {
        event.stopPropagation();
        if (open) {
            setOpen(false);
            setChildrenClosing(true);
            return;
        }
        setRenderChildren(true);
        setChildrenClosing(false);
        // 先把子节点挂载到关闭态，下一帧再打开，复刻 Vue Transition 的 enter 过渡。
        window.requestAnimationFrame(() => setOpen(true));
    }

    function handleChildrenTransitionEnd(event: React.TransitionEvent<HTMLDivElement>) {
        if (event.target !== event.currentTarget || !childrenClosing) return;
        setRenderChildren(false);
        setChildrenClosing(false);
    }

    if (item.status === "cancelled") return null;

    return (
        <div style={{ marginLeft: `${level * 24}px` }} className="SftpTransferItem transfer-item" onContextMenu={openContextMenu}>
            <div className="title-line">
                <div className={`line1 ${item.isDir ? "is-dir" : "is-file"}`}>
                    <div className="flex items-center gap-2">
                        {item.isDir ? <Icon icon={open ? "mdi:chevron-down" : "mdi:chevron-right"} className="group-ic" onClick={toggleChildren} /> : null}
                        <Icon icon={item.kind === "download" ? "mdi:download" : "mdi:upload"} className="group-ic" />
                        <span className="item-name truncate">{item.name}</span>
                    </div>
                    <div className="item-actions" onClick={(event) => event.stopPropagation()}>
                        {canPause ? (
                            <button type="button" className={`tx-btn${item.loadingFlag === "stop" ? " tx-btn--inline-loading" : ""}`} disabled={item.loadingFlag !== "none"} onClick={() => void item.stop()}>
                                {item.loadingFlag === "stop" ? <Icon icon="mdi:loading" className="tx-btn-load-ic" /> : null}
                                暂停
                            </button>
                        ) : null}
                        {canResume ? (
                            <button type="button" className="tx-btn" disabled={item.loadingFlag !== "none"} onClick={() => void item.resume()}>
                                继续
                            </button>
                        ) : null}
                        {canCancel ? (
                            <button type="button" className="tx-btn tx-btn--danger" disabled={item.loadingFlag !== "none"} onClick={() => void item.cancel()}>
                                取消
                            </button>
                        ) : null}
                        {canRetry ? (
                            <button type="button" className="tx-btn tx-btn--accent" onClick={() => void item.retry()}>
                                重试
                            </button>
                        ) : null}
                    </div>
                </div>
                <div className="line2 progress">
                    <div className="download-track">
                        <div key={item.loaded} className="download-bar" style={{ width: `${percent}%` }} />
                    </div>
                    <p className="bfb">{percent}%</p>
                    <span className="item-name size-name">{item.isDir ? `${item.loaded}/${item.total}` : `${formatAdaptiveBytes(item.loaded)}/${formatAdaptiveBytes(item.total ?? 0)}`}</span>
                    <div className="bps">{item.status === "running" ? formatSpeedBps(item.speedBps) : "0B/s"}</div>
                    <div className="remaining-time">{countdownText(item.remainingTime ?? 0)}</div>
                    <span className={`item-state ${item.status}`}>
                        {item.error} {statusText(item.status)}
                    </span>
                </div>
            </div>
            {renderChildren ? (
                <div className={`children ${open ? "children--open" : "children--closed"}`} onTransitionEnd={handleChildrenTransitionEnd}>
                    {item.children?.map((child) => (
                        <SftpTransferItem key={child.id} item={child} level={level + 1} />
                    ))}
                </div>
            ) : null}
        </div>
    );
}

// src/components/sftp/SftpTransferItem.vue
<script setup lang="ts">
import { baseName } from "@/utils/fsUtil";
import type { TransferUiItem } from ".";
import { formatAdaptiveBytes, formatSpeedBps } from "@/utils/project";
import { countdownText } from "@/utils";
import { openPath, revealItemInDir } from "@tauri-apps/plugin-opener";
import type { MenuItem } from "../DefaultMenuItems.vue";

const props = defineProps<{
    item: TransferUiItem;
    level: number;
}>();

const open = ref(true);

const canPause = computed(() => props.item.status === "running" || props.item.status === "queued");
const canResume = computed(() => props.item.status === "paused");
const canCancel = computed(() => ["running", "queued", "paused", "error"].includes(props.item.status));
const canRetry = computed(() => props.item.status === "error");

function statusText(status: TransferStatus): string {
    if (status === "running") return "进行中";
    if (status === "queued") return "排队";
    if (status === "paused") return "已暂停";
    if (status === "cancelled") return "已取消";
    if (status === "success") return "完成";
    return "失败";
}

async function handleOpenFile() {
    const localPath = props.item.localPath;
    if (!localPath || props.item.isDir) return;
    try {
        await openPath(localPath);
    } catch (e) {
        console.error(e);
        showToast(e instanceof Error ? e.message : "打开文件失败", "error");
    }
}

async function handleRevealInDir() {
    const localPath = props.item.localPath;
    if (!localPath) return;
    try {
        await revealItemInDir(localPath);
    } catch (e) {
        showToast(e instanceof Error ? e.message : "打开所在位置失败", "error");
    }
}

function openContextMenu(e: MouseEvent) {
    e.preventDefault();
    e.stopPropagation();
    const isFile = !props.item.isDir;
    const menus: MenuItem[] = [
        {
            label: "打开",
            disabled: !isFile,
            handler: () => void handleOpenFile(),
        },
        {
            label: "打开所在位置",
            handler: () => void handleRevealInDir(),
        },
        "---",
        {
            label: "取消并删除本地",
            handler: async () => {
                props.item.cancel();
                removeLocalIfAny(props.item.localPath);
            },
        },
    ];
    document.body.dispatchEvent(new CustomEvent(CustomMenusEventKey, { bubbles: true, detail: { menus, target: e } }));
}
</script>

<template>
    <div v-if="item.status !== 'cancelled'" :style="{ marginLeft: `${level * 24}px` }" class="transfer-item" @contextmenu="openContextMenu($event)">
        <div class="title-line">
            <div class="line1" :class="{ [item.isDir ? 'is-dir' : 'is-file']: true }">
                <div class="flex items-center gap-2">
                    <Icon v-if="item.isDir" :icon="open ? 'mdi:chevron-down' : 'mdi:chevron-right'" class="group-ic" @click.stop="open = !open" />
                    <Icon :icon="item.kind === 'download' ? 'mdi:download' : 'mdi:upload'" class="group-ic" />
                    <span class="item-name truncate">{{ item.name }}</span>
                </div>
                <div class="item-actions" @click.stop>
                    <button v-if="canPause" type="button" class="tx-btn" :class="{ 'tx-btn--inline-loading': item.loadingFlag === 'stop' }" :disabled="item.loadingFlag !== 'none'" @click="item.stop">
                        <Icon v-if="item.loadingFlag === 'stop'" icon="mdi:loading" class="tx-btn-load-ic" />
                        暂停
                    </button>
                    <button v-if="canResume" type="button" class="tx-btn" :disabled="item.loadingFlag !== 'none'" @click="item.resume">继续</button>
                    <button v-if="canCancel" type="button" class="tx-btn tx-btn--danger" :disabled="item.loadingFlag !== 'none'" @click="item.cancel">取消</button>
                    <button v-if="canRetry" type="button" class="tx-btn tx-btn--accent" @click="item.retry">重试</button>
                </div>
            </div>
            <div class="line2 progress">
                <div class="download-track"><div class="download-bar" :key="item.loaded" :style="{ width: `${((item.loaded / (item.total || 1)) * 100).toFixed(2)}%` }" /></div>
                <p class="bfb">{{ ((item.loaded / (item.total || 1)) * 100).toFixed(2) }}%</p>
                <span v-if="item.isDir" class="item-name size-name">{{ item.loaded }}/{{ item.total }}</span>
                <span v-else class="item-name size-name">{{ formatAdaptiveBytes(item.loaded) }}/{{ formatAdaptiveBytes(item.total) }}</span>
                <div v-if="item.status === 'running'" class="bps">{{ formatSpeedBps(item.speedBps) }}</div>
                <div v-else class="bps">0B/s</div>
                <div v-if="item.status === 'running'" class="remaining-time">{{ countdownText(item.remainingTime ?? 0) }}</div>
                <div v-else class="remaining-time">{{ countdownText(item.remainingTime ?? 0) }}</div>
                <span class="item-state" :class="item.status">{{ item.error }} {{ statusText(item.status) }}</span>
            </div>
        </div>
        <Transition name="children-collapse">
            <div v-if="open" class="children">
                <SftpTransferItem v-for="child in item.children" :key="child.id" :item="child" :level="level + 1" />
            </div>
        </Transition>
    </div>
</template>

<style scoped lang="scss">
.transfer-item {
    margin: 8px 0;
    border-radius: 8px;
    padding: 8px 0px 8px 10px;
    .title-line {
        width: 98%;
    }
    .line1 {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .line2 {
        margin-top: 8px;
    }
}

.progress {
    display: flex;
    align-items: center;
    .download-track {
        height: 4px;
        border-radius: 999px;
        flex-grow: 1;
        overflow: hidden;
    }

    .bfb {
        text-align: center;
        width: 6em;
    }
    .size-name {
        width: 12em;
    }
    .bps {
        width: 8em;
    }
    .item-state {
        width: 6rem;
        text-align: right;
        flex-shrink: 0;
    }
}

.group-ic {
    font-size: var(--font-size-2xl);
    flex-shrink: 0;
}
.download-bar {
    height: 100%;
    transition: width 0.2s ease;
}
.item-actions {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
    flex-shrink: 0;
    max-width: 100%;
}

.tx-btn--inline-loading {
    display: inline-flex;
    align-items: center;
    gap: 4px;
}
.tx-btn-load-ic {
    flex-shrink: 0;
    opacity: 0.9;
    animation: sftp-tx-spin 0.85s linear infinite;
}
@keyframes sftp-tx-spin {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
    }
}
.tx-btn {
    font-size: var(--font-size-2xs);
    line-height: 1.2;
    padding: 2px 6px;
    border-radius: 4px;
    cursor: pointer;
    white-space: nowrap;
}
.tx-btn:disabled {
    opacity: 0.42;
    cursor: not-allowed;
    pointer-events: none;
}
.tx-btn--danger {
}
.tx-btn--accent {
}

.children-collapse-enter-active,
.children-collapse-leave-active {
    transition:
        max-height 0.25s ease,
        opacity 0.22s ease,
        margin-top 0.25s ease;
    overflow: hidden;
}
.children-collapse-enter-from,
.children-collapse-leave-to {
    max-height: 0;
    opacity: 0;
    margin-top: 0;
}
.children-collapse-enter-to,
.children-collapse-leave-from {
    max-height: 1200px;
    opacity: 1;
    margin-top: 4px;
}
</style>
