// web-next/src/components/monaco/MonacoEditor/index.tsx
"use client";

import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import { useConfigStore } from "@/stores/config";
import { DEFAULT_FONT_FAMILY } from "@/utils/constant";
import { defineKerayMonacoTheme, languageFromPath } from "@/components/monaco/monacoEnv";
import "./index.scss";

/** 单个打开文件的模型描述 */
export type MonacoEditorModelSpec = {
    key: string;
    path: string;
    content: string;
    language?: string;
    readOnly?: boolean;
};

export type MonacoEditorExpose = {
    getContent: () => string;
    focus: () => void;
};

export type MonacoEditorProps = {
    file: MonacoEditorModelSpec;
    className?: string;
    style?: React.CSSProperties;
    onChange: (content: string) => void;
    onSave: () => void;
};

function modelUri(monaco: typeof import("monaco-editor"), path: string) {
    const lang = languageFromPath(path);
    return monaco.Uri.parse(`file:///${path.replace(/^\//, "")}.${lang === "shell" ? "txt" : lang}`);
}

const MonacoEditor = forwardRef<MonacoEditorExpose, MonacoEditorProps>(function MonacoEditor({ file, className, style, onChange, onSave }, ref) {
    const hostRef = useRef<HTMLDivElement | null>(null);
    const monacoRef = useRef<typeof import("monaco-editor") | null>(null);
    const editorRef = useRef<import("monaco-editor").editor.IStandaloneCodeEditor | null>(null);
    const modelRef = useRef<import("monaco-editor").editor.ITextModel | null>(null);
    const fileRef = useRef(file);
    const onChangeRef = useRef(onChange);
    const onSaveRef = useRef(onSave);
    const themeMode = useConfigStore((state) => state.themeMode);
    const fontSize = useConfigStore((state) => state.fontSize);
    const termFontFamily = useConfigStore((state) => state.termFontFamily);

    useImperativeHandle(ref, () => ({
        getContent: () => modelRef.current?.getValue() ?? fileRef.current.content,
        focus: () => editorRef.current?.focus(),
    }));

    function syncEditorFromFile() {
        const monaco = monacoRef.current;
        const editor = editorRef.current;
        const model = modelRef.current;
        const currentFile = fileRef.current;
        if (!monaco || !editor || !model) return;
        if (model.getValue() !== currentFile.content) model.setValue(currentFile.content);
        monaco.editor.setModelLanguage(model, currentFile.language ?? languageFromPath(currentFile.path));
        editor.updateOptions({ readOnly: Boolean(currentFile.readOnly) });
    }

    useEffect(() => {
        let disposed = false;
        let resizeObserver: ResizeObserver | null = null;
        let saveAction: import("monaco-editor").IDisposable | null = null;
        let contentListener: import("monaco-editor").IDisposable | null = null;

        async function initEditor() {
            const host = hostRef.current;
            if (!host || editorRef.current) return;
            await import("@/components/monaco/monacoNls");
            const monaco = await import("monaco-editor");
            if (disposed) return;
            monacoRef.current = monaco;
            defineKerayMonacoTheme(monaco, document.documentElement, themeMode);
            // Monaco 通过异步 import 初始化；期间 file 可能已从“加载中”更新为真实内容，必须取最新 ref。
            const currentFile = fileRef.current;
            const model = monaco.editor.createModel(currentFile.content, currentFile.language ?? languageFromPath(currentFile.path), modelUri(monaco, currentFile.path));
            const editor = monaco.editor.create(host, {
                model,
                automaticLayout: false,
                fontSize,
                fontFamily: termFontFamily || DEFAULT_FONT_FAMILY,
                lineHeight: Math.round(fontSize * 1.45),
                minimap: { enabled: true, scale: 0.5 },
                scrollBeyondLastLine: false,
                wordWrap: "off",
                tabSize: 4,
                insertSpaces: true,
                renderWhitespace: "selection",
                smoothScrolling: true,
                cursorBlinking: "smooth",
                padding: { top: 8, bottom: 8 },
                overviewRulerLanes: 0,
                readOnly: Boolean(currentFile.readOnly),
            });
            editorRef.current = editor;
            modelRef.current = model;
            saveAction = editor.addAction({
                id: "keray-save",
                label: "保存",
                keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS],
                run: () => onSaveRef.current(),
            });
            contentListener = editor.onDidChangeModelContent(() => {
                const nextModel = editor.getModel();
                if (nextModel) onChangeRef.current(nextModel.getValue());
            });
            resizeObserver = new ResizeObserver(() => editor.layout());
            resizeObserver.observe(host);
            syncEditorFromFile();
        }

        void initEditor();
        return () => {
            disposed = true;
            saveAction?.dispose();
            contentListener?.dispose();
            resizeObserver?.disconnect();
            modelRef.current?.dispose();
            editorRef.current?.dispose();
            modelRef.current = null;
            editorRef.current = null;
        };
        // Monaco 实例必须随 DOM host 只创建一次；内容、主题和字体通过后续 effects 同步。
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        fileRef.current = file;
        syncEditorFromFile();
    }, [file]);

    useEffect(() => {
        onChangeRef.current = onChange;
    }, [onChange]);

    useEffect(() => {
        onSaveRef.current = onSave;
    }, [onSave]);

    useEffect(() => {
        const monaco = monacoRef.current;
        if (monaco) defineKerayMonacoTheme(monaco, document.documentElement, themeMode);
    }, [themeMode]);

    useEffect(() => {
        editorRef.current?.updateOptions({
            fontSize,
            lineHeight: Math.round(fontSize * 1.45),
            fontFamily: termFontFamily || DEFAULT_FONT_FAMILY,
        });
    }, [fontSize, termFontFamily]);

    return <div ref={hostRef} className={className ? `MonacoEditor monaco-editor-host ${className}` : "MonacoEditor monaco-editor-host"} style={style} />;
});

export default MonacoEditor;

// src/components/monaco/MonacoEditor.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { defineKerayMonacoTheme, languageFromPath, monaco } from "@/components/monaco/monacoEnv";
import "monaco-editor/min/vs/editor/editor.main.css";
import { DEFAULT_FONT_FAMILY } from "@/utils/constant";

defineOptions({
    name: "MonacoEditor",
});

/** 单个打开文件的模型描述 */
export type MonacoEditorModelSpec = {
    key: string;
    path: string;
    content: string;
    language?: string;
    readOnly?: boolean;
};

const props = defineProps<{
    /** 当前 editor 负责的单个文件 */
    file: MonacoEditorModelSpec;
}>();

const emit = defineEmits<{
    /** 文本变更：回传最新内容 */
    change: [content: string];
    /** Ctrl/Cmd + S */
    save: [];
    ready: [];
}>();

const configStore = useConfigStore();
const { themeMode, fontSize, termFontFamily } = storeToRefs(configStore);

const hostRef = ref<HTMLElement | null>(null);
const editorRef = shallowRef<monaco.editor.IStandaloneCodeEditor | null>(null);
const modelRef = shallowRef<monaco.editor.ITextModel | null>(null);

let saveAction: monaco.IDisposable | null = null;
let contentListener: monaco.IDisposable | null = null;
let resizeObserver: ResizeObserver | null = null;

/** 构建 model URI，便于 Monaco 按语言提供语法服务 */
function modelUri(path: string) {
    const lang = languageFromPath(path);
    return monaco.Uri.parse(`file:///${path.replace(/^\//, "")}.${lang === "shell" ? "txt" : lang}`);
}

/** 同步外部文件状态到当前 editor 的 model */
function syncModelContent() {
    const editor = editorRef.value;
    const model = modelRef.value;
    const spec = props.file;
    if (!editor || !model) return;

    if (model.getValue() !== spec.content) {
        model.setValue(spec.content);
    }
    monaco.editor.setModelLanguage(model, spec.language ?? languageFromPath(spec.path));
    editor.updateOptions({ readOnly: Boolean(spec.readOnly) });
}

/** 初始化 Monaco 实例 */
function initEditor() {
    const host = hostRef.value;
    if (!host || editorRef.value) return;

    defineKerayMonacoTheme(document.documentElement, themeMode.value);

    const editor = monaco.editor.create(host, {
        model: monaco.editor.createModel(props.file.content, props.file.language ?? languageFromPath(props.file.path), modelUri(props.file.path)),
        automaticLayout: false,
        fontSize: fontSize.value,
        fontFamily: termFontFamily.value || DEFAULT_FONT_FAMILY,
        lineHeight: Math.round(fontSize.value * 1.45),
        minimap: { enabled: true, scale: 0.5 },
        scrollBeyondLastLine: false,
        wordWrap: "off",
        tabSize: 4,
        insertSpaces: true,
        renderWhitespace: "selection",
        smoothScrolling: true,
        cursorBlinking: "smooth",
        padding: { top: 8, bottom: 8 },
        overviewRulerLanes: 0,
    });

    editorRef.value = editor;
    modelRef.value = editor.getModel();

    // 注册保存快捷键（Ctrl/Cmd + S）
    saveAction = editor.addAction({
        id: "keray-save",
        label: "保存",
        keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS],
        run: () => {
            emit("save");
        },
    });

    contentListener = editor.onDidChangeModelContent(() => {
        const model = editor.getModel();
        if (!model) return;
        emit("change", model.getValue());
    });

    resizeObserver = new ResizeObserver(() => editor.layout());
    resizeObserver.observe(host);

    syncModelContent();
    emit("ready");
}

/** 读取当前文件的最新内容（保存时使用） */
function getContent(): string {
    return modelRef.value?.getValue() ?? props.file.content;
}

defineExpose({
    getContent,
    focus: () => editorRef.value?.focus(),
});

watch(
    () => props.file,
    () => syncModelContent(),
    { deep: true },
);

watch(themeMode, (mode) => {
    defineKerayMonacoTheme(document.documentElement, mode);
});

watch([fontSize, termFontFamily], ([size, family]) => {
    editorRef.value?.updateOptions({
        fontSize: size,
        lineHeight: Math.round(size * 1.45),
        fontFamily: family || DEFAULT_FONT_FAMILY,
    });
});

onMounted(() => {
    initEditor();
});

onBeforeUnmount(() => {
    saveAction?.dispose();
    contentListener?.dispose();
    resizeObserver?.disconnect();
    modelRef.value?.dispose();
    modelRef.value = null;
    editorRef.value?.dispose();
    editorRef.value = null;
});
</script>

<template>
    <div ref="hostRef" class="monaco-editor-host"></div>
</template>

<style scoped lang="scss">
.monaco-editor-host {
    width: 100%;
    height: 100%;
    min-height: 0;
    overflow: hidden;
}
</style>
<style lang="scss">
.monaco-editor-host {
    .monaco-editor,
    .monaco-editor-background,
    .margin {
        background-color: transparent !important;
    }
    .view-overlays {
        > div {
            background-color: transparent !important;
        }
        .current-line {
            background-color: transparent !important;
        }
    }
    .minimap {
        left: unset !important;
        right: 0px !important;
        width: 60px !important;
        backdrop-filter: blur(1px);
    }
}
</style>
