// src/components/ssh/term.vue
<script setup lang="ts">
import { ChannelInstanceProvideKey, CustomMenusEventKey, DEFAULT_FONT_FAMILY } from "@/utils/constant";
import TermServer, { type TerminalSnapshot } from "./term_server";
import "@xterm/xterm/css/xterm.css";
import { storeToRefs } from "pinia";
import type { UnlistenFn } from "@tauri-apps/api/event";
import useBus, { DirectRemotePathEventKey, TermGroupCommandEventKey } from "@/composables/useBus";
import type { SystemInputExpose } from "../SystemInput.vue";

const props = withDefaults(
    defineProps<{
        server: ChannelInstance;
        groupId?: string;
        groupActive?: boolean;
    }>(),
    {
        isGroup: false,
        groupActive: false,
    },
);
const appStore = useAppStore();
const configStore = useConfigStore();
const serverDataStore = useServerDataStore();
const keyEventStore = useKeyEventStore();
const { emit, on, off } = useBus();
const { showSftpPanel, showTermPanel } = storeToRefs(appStore);
const { termFontSize, termLineHeight, termFontFamily, termScrollback, sftpPanelHeightPx } = storeToRefs(configStore);
const { serverDataChange } = serverDataStore;

let termServer: TermServer;

const termReady = ref(false);
function writeToTerm(cmd: string) {
    termServer?.write(cmd);
}

const divRef = ref<HTMLElement>();
const lineNumber = ref<HTMLElement>();
const root = ref<HTMLDivElement>();
const searchInput = ref<SystemInputExpose>();
const panelRoot = ref<HTMLDivElement>();

let selectedText = "";
const mousePos = { x: 0, y: 0 };
const searchData = reactive({
    text: "",
    index: 0,
    show: false,
    count: 0,
    wholeWord: false,
    regex: false,
    caseSensitive: false,
});
const selectPrompt = reactive({
    show: false,
    x: 0,
    y: 0,
    text: "",
});
const searchIsFocus = ref(false);

type DragStartSnapshot = {
    termData: TerminalSnapshot;
    webData: {
        searchData: typeof searchData;
        selectPrompt: typeof selectPrompt;
        searchIsFocus: boolean;
    };
};
const closeFuns: UnlistenFn[] = [];

const termConfig = computed(() => {
    return {
        fontSize: termFontSize.value,
        lineHeight: termLineHeight.value,
        fontFamily: termFontFamily.value || DEFAULT_FONT_FAMILY,
        scrollback: termScrollback.value,
    };
});

watch(
    () => searchData.show,
    (val) => {
        if (!val) {
            searchData.text = "";
            searchData.count = 0;
            termServer.clearDecorations();
        }
    },
);

watch(termConfig, () => {
    termServer?.settingConfig(termConfig.value);
});

// 按esc键
function enterEsc() {
    if (searchData.show) searchData.show = false;
    if (selectPrompt.show) selectPrompt.show = false;
}

function updateLineNumbers({ nums, height, fontSize }: { nums: Array<[number, number]>; height: number; fontSize: number }) {
    let html = "";
    for (const [showNum, realNum] of nums) {
        html += `<div class="num" style="height:${height}px;font-size:${fontSize}px" line="${realNum}">${showNum}</div>`;
    }
    if (!lineNumber.value) return;
    lineNumber.value!.innerHTML = html;
}

function termServerEventListen() {
    termServer.onLineNumberChange(updateLineNumbers);
    // 响应win系统的ctrl+c
    termServer.onKeyEvent(termKeydown);
    termServer.onSelectionChange((text) => {
        selectedText = text;
        selectPrompt.text = selectedText;
        const show = Boolean(selectedText);
        selectPrompt.show = false;
        if (!mousePos.x) return;
        selectPrompt.show = show;
        selectPrompt.x = mousePos.x;
        selectPrompt.y = mousePos.y;
    });
    termServer.onCwdChange((path) => {
        emit(DirectRemotePathEventKey, { sid: props.server.sessionId, path });
    });
    termServer.onData((command) => {
        if (!props.groupId) return;
        emit(TermGroupCommandEventKey, { groupId: props.groupId!, command, sessionId: props.server.sessionId });
    });
    termServer.onSearchChange((count, index) => {
        searchData.count = count;
        searchData.index = index + 1;
    });
    closeFuns.push(
        on(TermGroupCommandEventKey, (event) => {
            if (event.groupId !== props.groupId) return;
            if (event.sessionId === props.server.sessionId) return;
            termServer.write(event.command);
        }),
    );
}
function termChangeFontSize(add: number) {
    const size = termServer.changeFontSize(add);
    if (size) {
        configStore.changeConfig({
            termFontSize: size,
        });
    }
}
function domEventListen() {
    {
        let scale = 1;
        root.value!.addEventListener("gesturechange", (e: any) => {
            e.preventDefault();
            termChangeFontSize(10 * (e.scale - scale));
            scale = e.scale;
        });
        root.value!.addEventListener("gesturestart", (e: any) => {
            e.preventDefault();
            scale = e.scale;
        });
    }

    root.value!.addEventListener("mouseup", (e: MouseEvent) => {
        if (eventHave(e, divRef.value!)) {
            mousePos.x = e.clientX;
            mousePos.y = e.clientY;
        } else {
            mousePos.x = 0;
        }
    });
    divRef.value!.addEventListener("contextmenu", (e: MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        selectPrompt.show = false;
        document.body.dispatchEvent(
            new CustomEvent(CustomMenusEventKey, {
                bubbles: true,
                detail: {
                    menus: menusConfig.value,
                    target: e,
                },
            }),
        );
    });
    // 响应mac的command
    closeFuns.push(
        keyEventStore.register((e) => {
            return termKeydown(e);
        }),
    );
}

function termKeydown(e: KeyboardEvent): boolean {
    const target = e.target as HTMLElement;
    if (!root.value!.contains(target)) return false;
    // 处理部分快捷键
    // command+f
    const curl = e.ctrlKey || e.metaKey;
    if (curl) {
        if (e.key === "f") {
            if (!searchData.text || selectedText) searchData.text = selectedText;
            search();
        } else if (e.key === "v") {
            ctrlV();
        } else if (e.key === "c") {
            ctrlC();
        } else if (e.key === "=") {
            termChangeFontSize(1);
        } else if (e.key === "-") {
            termChangeFontSize(-1);
        } else if (e.key === "0") {
            termChangeFontSize(0);
        } else {
            return false;
        }
        return true;
    } else if (e.key === "Escape") {
        enterEsc();
        return true;
    }
    return false;
}

async function ctrlV() {
    const text = await readClipboardText();
    termServer.write(text);
}

async function ctrlC() {
    if (!selectPrompt.text) return;
    copyText(selectPrompt.text);
}

const clickSearch = (next: boolean) => {
    const options = {
        regex: searchData.regex,
        caseSensitive: searchData.caseSensitive,
        wholeWord: searchData.wholeWord,
    };
    const fun = next ? termServer.findNext : termServer.findPrevious;
    fun.bind(termServer)(searchData.text, options);
};

const search = () => {
    mousePos.x = 0; // 打开搜索时关闭坐标信息 避免粘贴提示显示
    searchData.show = true;
    termServer.clearDecorations();
    clickSearch(true);
    nextTick(() => {
        searchInput.value!.focus();
    });
};

const clickCopyText = () => {
    copyText(selectPrompt.text);
    termServer.clearSelection();
};

const applyText = () => {
    termServer.write(selectPrompt.text);
    termServer.clearSelection();
};

const applySearch = () => {
    searchData.text = selectPrompt.text;
    search();
    search();
};

const selectLine = (e: MouseEvent) => {
    const line = parseInt((e.target as HTMLElement).getAttribute("line") || "0");
    termServer.selectLines(line - 1, line - 1);
};

const menuLineNumber = (e: MouseEvent) => {
    const line = parseInt((e.target as HTMLElement).getAttribute("line") || "0");
    termServer.settingZeroLine(line);
};

onMounted(async () => {
    termServer = new TermServer({ server: props.server });
    closeFuns.push(termServer.close);
    props.server.snapshotFn.termData = () => {
        return {
            termData: termServer.snapshot(),
            webData: {
                searchData: searchData,
                selectPrompt: selectPrompt,
                searchIsFocus: searchIsFocus.value,
            },
        } as DragStartSnapshot;
    };
    termServer.settingConfig(termConfig.value);
    const noSnapshot = !(await sid_new_window_init());
    if (noSnapshot) {
        termServer.initTerminal(divRef.value!);
    }
    await termServer.connect(noSnapshot);
    if (noSnapshot) {
        props.server.server.lastConnectAt = Date.now();
        serverDataChange(props.server.server);
    }
    termServerEventListen();
    domEventListen();
    termReady.value = true;
});

onBeforeUnmount(() => {
    closeFuns.forEach((unlisten) => unlisten());
});

async function sid_new_window_init() {
    const server = props.server;
    const snapshot = server.snapshot.termData as DragStartSnapshot | undefined;
    if (!snapshot) return false;
    const { termData, webData } = snapshot;
    // 快照用了就要删除
    delete server.snapshot.termData;
    termServer.snapshotReset(termData, divRef.value!);
    Object.assign(searchData, webData.searchData);
    Object.assign(selectPrompt, webData.selectPrompt);
    if (searchData.text) {
        clickSearch(true);
        searchData.count = webData.searchData.count;
        searchData.index = webData.searchData.index;
    }
    searchIsFocus.value = webData.searchIsFocus;
    if (searchIsFocus.value) {
        nextTick(() => {
            searchInput.value!.focus();
        });
    }
    return true;
}

const menusConfig = computed(() => {
    return [
        {
            label: "复制",
            disabled: !selectPrompt.text,
            handler: () => {
                ctrlC();
            },
        },
        {
            label: "粘贴",
            handler: async () => {
                ctrlV();
            },
        },
        {
            label: "粘贴选中",
            disabled: !selectPrompt.text,
            handler: () => {
                applyText();
            },
        },
        "---",
        {
            label: "查找",
            handler: () => {
                applySearch();
            },
        },
        "---",
        {
            label: "清空缓存",
            handler: async () => {
                termServer.clear();
                if (searchData.count > 0) {
                    termServer.resetSearch();
                    search();
                }
            },
        },
        "---",
        {
            label: "设置",
            handler: () => {
                openOrFocusSettingsWindow("terminal");
            },
        },
    ];
});

provide(ChannelInstanceProvideKey, props.server);
</script>

<template>
    <div ref="panelRoot" class="relative flex h-full w-full min-h-0 flex-col overflow-hidden">
        <div v-show="showTermPanel || groupId" class="relative viwer root term-module min-h-0 flex-1 overflow-hidden" ref="root">
            <div v-if="!groupId || groupActive" ref="lineNumber" class="line-number" @click="selectLine" @contextmenu="menuLineNumber"></div>
            <div class="term" ref="divRef"></div>
            <div v-show="searchData.show" class="search">
                <div class="grow flex justify-between items-center ml-2 left">
                    <Icon icon="si:search-alt-fill" class="mr-1" />
                    <!-- 搜索内容需要严格保留用户输入的大小写，避免 macOS/WebKit 按自然语言自动改写。 -->
                    <SystemInput ref="searchInput" v-model="searchData.text" class="grow w-full" @input="search" @focus="searchIsFocus = true" @blur="searchIsFocus = false" />
                    <Icon
                        icon="mdi:format-lowercase"
                        class="pointer icon"
                        :class="{ active: searchData.caseSensitive }"
                        @click="
                            searchData.caseSensitive = !searchData.caseSensitive;
                            search();
                        "
                    />
                    <Icon
                        icon="icon-park-solid:word"
                        class="pointer icon"
                        :class="{ active: searchData.wholeWord }"
                        @click="
                            searchData.wholeWord = !searchData.wholeWord;
                            search();
                        "
                    />
                    <Icon
                        icon="mdi:regex"
                        class="pointer icon"
                        :class="{ active: searchData.regex }"
                        @click="
                            searchData.regex = !searchData.regex;
                            search();
                        "
                    />
                    <p class="cnt">
                        {{ searchData.count ? `${searchData.index}/${searchData.count}` : "0" }}
                    </p>
                </div>
                <div class="flex justify-center items-center">
                    <Icon icon="si:expand-less-fill" class="pointer icon" @click="clickSearch(false)" />
                    <Icon icon="si:expand-more-fill" class="pointer icon" @click="clickSearch(true)" />
                    <Icon icon="si:close-duotone" class="pointer icon" @click="searchData.show = false" />
                </div>
            </div>
            <div v-if="selectPrompt.show" class="select-prompt flex" :style="{ left: selectPrompt.x + 'px', top: selectPrompt.y + 10 + 'px' }">
                <Icon icon="si:copy-alt-duotone" class="pointer icon" @click.stop="clickCopyText" />
                <Icon icon="si:copy-fill" class="pointer icon" @click.stop="applyText" />
                <Icon icon="si:search-alt-fill" class="pointer icon" @click.stop="applySearch" />
            </div>
        </div>
        <template v-if="termReady && !groupId">
            <LayoutRowResizer v-show="showSftpPanel && showTermPanel" :container="panelRoot" v-model="sftpPanelHeightPx" />
            <div v-show="showSftpPanel" class="overflow-hidden" :class="{ 'min-h-0 flex-1': !showTermPanel }" :style="showTermPanel ? { height: `${sftpPanelHeightPx}px` } : {}">
                <Sftp class="h-full min-h-0" :server="server" :write-terminal="writeToTerm" />
            </div>
        </template>
    </div>
</template>

<style scoped lang="scss">
.term-module:deep() {
    border-radius: 8px;
    padding: 8px;
    min-height: 0;
    flex: 1 1 0%;

    .line-number {
        margin-top: 8px;
        position: absolute;
        left: 0;
        top: 0;
        z-index: 2;
        width: 34px;
        height: 100%;

        .num {
            cursor: alias;
            display: flex;
            align-items: center;
            justify-content: end;
        }
    }

    .term {
        width: 100%;
        height: 100%;
        padding-left: 30px;

        .xterm-viewport,
        .xterm-scrollable-element {
            background-color: transparent !important;
        }
    }

    .search {
        position: absolute;
        z-index: 2;
        top: 10px;
        right: 10px;
        min-width: 200px;
        max-width: 400px;
        width: 30%;
        height: 26px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-radius: 5px;

        .left {
            .icon {
                margin-right: 4px;
            }
        }

        .cnt {
            white-space: nowrap;
            opacity: 1;
            width: 5em;
            text-align: center;
        }

        .icon {
            font-size: var(--font-size-2xl);
            width: 16px;
            height: 16px;
            margin-left: 3px;
        }
    }

    .select-prompt {
        position: fixed;
        z-index: 2000;
        padding: 3px;
        border-radius: 7px;

        .icon {
            font-size: var(--font-size-4xl);
            margin: 0 5px;
            display: inline-block;
        }
    }
    .term {
        .scrollbar {
            width: 6px !important;
            right: -4px !important;
            .slider {
                width: 6px !important;
                border-radius: 3px !important;
            }
        }
    }
}
</style>

// web-next/src/components/ssh/Term/index.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Icon from "@/components/Icon";
import LayoutRowResizer from "@/components/layout/LayoutRowResizer";
import Sftp from "@/components/sftp/Sftp";
import SystemInput, { type SystemInputExpose } from "@/components/SystemInput";
import useBus, { DirectRemotePathEventKey, TermGroupCommandEventKey } from "@/hooks/useBus";
import { useAppStore } from "@/stores/app";
import { useConfigStore } from "@/stores/config";
import { useKeyEventStore } from "@/stores/keyEvent";
import type { ChannelInstance } from "@/stores/channelInstances";
import { useServerDataStore } from "@/stores/serverData";
import { CustomMenusEventKey, DEFAULT_FONT_FAMILY } from "@/utils/constant";
import { copyText, eventHave, readClipboardText } from "@/utils/project";
import { showToast } from "@/utils/ui";
import { openOrFocusSettingsWindow } from "@/utils/window";
import type TermServer from "@/components/ssh/term_server";
import type { TerminalSnapshot } from "@/components/ssh/term_server";
import "./index.scss";

export type TermProps = {
    server: ChannelInstance;
    groupId?: string;
    groupActive?: boolean;
};

type SearchData = {
    text: string;
    index: number;
    show: boolean;
    count: number;
    wholeWord: boolean;
    regex: boolean;
    caseSensitive: boolean;
};

type WebKitGestureEvent = Event & {
    scale?: number;
};

const emptySearchData = (): SearchData => ({
    text: "",
    index: 0,
    show: false,
    count: 0,
    wholeWord: false,
    regex: false,
    caseSensitive: false,
});

export default function Term({ server, groupId, groupActive }: TermProps) {
    const divRef = useRef<HTMLDivElement | null>(null);
    const lineNumber = useRef<HTMLDivElement | null>(null);
    const root = useRef<HTMLDivElement | null>(null);
    const searchInput = useRef<SystemInputExpose | null>(null);
    const panelRoot = useRef<HTMLDivElement | null>(null);
    const termServer = useRef<TermServer | null>(null);
    const selectedText = useRef("");
    const mousePos = useRef({ x: 0, y: 0 });
    const searchDataRef = useRef<SearchData>(emptySearchData());
    const searchIsFocusRef = useRef(false);
    const selectPromptRef = useRef({ show: false, x: 0, y: 0, text: "" });
    const [ready, setReady] = useState(false);
    const [searchData, setSearchData] = useState<SearchData>(() => emptySearchData());
    const [, setSearchIsFocus] = useState(false);
    const [selectPrompt, setSelectPrompt] = useState({ show: false, x: 0, y: 0, text: "" });
    const showTermPanel = useAppStore((state) => state.showTermPanel);
    const showSftpPanel = useAppStore((state) => state.showSftpPanel);
    const termFontSize = useConfigStore((state) => state.termFontSize);
    const termLineHeight = useConfigStore((state) => state.termLineHeight);
    const termFontFamily = useConfigStore((state) => state.termFontFamily);
    const termScrollback = useConfigStore((state) => state.termScrollback);
    const sftpPanelHeightPx = useConfigStore((state) => state.sftpPanelHeightPx);
    const changeConfig = useConfigStore((state) => state.changeConfig);
    const registerKeyEvent = useKeyEventStore((state) => state.register);
    const { emit, on } = useBus();

    const termConfig = useMemo(
        () => ({
            fontSize: termFontSize,
            lineHeight: termLineHeight,
            fontFamily: termFontFamily || DEFAULT_FONT_FAMILY,
            scrollback: termScrollback,
        }),
        [termFontFamily, termFontSize, termLineHeight, termScrollback],
    );

    function updateLineNumbers({ nums, height, fontSize }: { nums: Array<[number, number]>; height: number; fontSize: number }) {
        if (!lineNumber.current) return;
        lineNumber.current.innerHTML = nums.map(([showNum, realNum]) => `<div class="num" style="height:${height}px;font-size:${fontSize}px" line="${realNum}">${showNum}</div>`).join("");
    }

    function termChangeFontSize(add: number) {
        const size = termServer.current?.changeFontSize(add);
        if (size) changeConfig({ termFontSize: size });
    }

    function writeToTerm(cmd: string) {
        void termServer.current?.write(cmd);
    }

    function setSearchDataSync(next: SearchData | ((prev: SearchData) => SearchData)) {
        const value = typeof next === "function" ? next(searchDataRef.current) : next;
        searchDataRef.current = value;
        setSearchData(value);
    }

    function setSelectPromptSync(next: typeof selectPrompt | ((prev: typeof selectPrompt) => typeof selectPrompt)) {
        const value = typeof next === "function" ? next(selectPromptRef.current) : next;
        selectPromptRef.current = value;
        setSelectPrompt(value);
    }

    function setSearchFocusSync(value: boolean) {
        searchIsFocusRef.current = value;
        setSearchIsFocus(value);
    }

    async function ctrlV() {
        const text = await readClipboardText();
        termServer.current?._onData(text);
    }

    function ctrlC() {
        if (!selectedText.current) return;
        void copyText(selectedText.current);
    }

    function termKeydown(e: KeyboardEvent): boolean {
        const target = e.target as HTMLElement;
        if (!root.current?.contains(target)) return false;
        const curl = e.ctrlKey || e.metaKey;
        if (curl) {
            if (e.key === "f") {
                if (!searchDataRef.current.text || selectedText.current) {
                    setSearchDataSync((prev) => ({ ...prev, text: selectedText.current }));
                }
                search();
            } else if (e.key === "v") void ctrlV();
            else if (e.key === "c") ctrlC();
            else if (e.key === "=") termChangeFontSize(1);
            else if (e.key === "-") termChangeFontSize(-1);
            else if (e.key === "0") termChangeFontSize(0);
            else return false;
            return true;
        }
        if (e.key === "Escape") {
            if (searchDataRef.current.show) hideSearch();
            setSelectPromptSync((prev) => ({ ...prev, show: false }));
            return true;
        }
        return false;
    }

    function clickCopyText() {
        void copyText(selectPromptRef.current.text);
        termServer.current?.clearSelection();
    }

    function applyText() {
        void termServer.current?.write(selectPromptRef.current.text);
        termServer.current?.clearSelection();
    }

    function searchOptions(data = searchDataRef.current) {
        return {
            regex: data.regex,
            caseSensitive: data.caseSensitive,
            wholeWord: data.wholeWord,
        };
    }

    function clickSearch(next: boolean, data = searchDataRef.current) {
        const instance = termServer.current;
        if (!instance) return;
        const fn = next ? instance.findNext : instance.findPrevious;
        fn.bind(instance)(data.text, searchOptions(data));
    }

    function focusSearchInput() {
        window.setTimeout(() => searchInput.current?.focus(), 0);
    }

    function search(nextData = searchDataRef.current) {
        const instance = termServer.current;
        if (!instance) return;
        mousePos.current = { x: 0, y: 0 };
        const data = { ...nextData, show: true };
        setSearchDataSync(data);
        instance.clearDecorations();
        clickSearch(true, data);
        focusSearchInput();
    }

    function hideSearch() {
        termServer.current?.clearDecorations();
        setSearchDataSync({ ...searchDataRef.current, text: "", count: 0, show: false });
    }

    function updateSearch(patch: Partial<SearchData>) {
        const data = { ...searchDataRef.current, ...patch };
        search(data);
    }

    function applySearch() {
        const data = { ...searchDataRef.current, text: selectPromptRef.current.text };
        setSearchDataSync(data);
        search(data);
        search(data);
    }

    function openContextMenu(e: MouseEvent) {
        e.preventDefault();
        e.stopPropagation();
        setSelectPromptSync((prev) => ({ ...prev, show: false }));
        document.body.dispatchEvent(
            new CustomEvent(CustomMenusEventKey, {
                bubbles: true,
                detail: {
                    menus: [
                        { label: "复制", disabled: !selectedText.current, handler: ctrlC },
                        { label: "粘贴", handler: () => void ctrlV() },
                        { label: "粘贴选中", disabled: !selectedText.current, handler: applyText },
                        "---",
                        { label: "查找", handler: applySearch },
                        "---",
                        {
                            label: "清空缓存",
                            handler: () => {
                                termServer.current?.clear();
                                if (searchDataRef.current.count > 0) {
                                    termServer.current?.resetSearch();
                                    search();
                                }
                            },
                        },
                        "---",
                        {
                            label: "设置",
                            handler: () => void openOrFocusSettingsWindow("terminal"),
                        },
                    ],
                    target: e,
                },
            }),
        );
    }

    function selectLine(e: React.MouseEvent) {
        const line = parseInt((e.target as HTMLElement).getAttribute("line") || "0");
        termServer.current?.selectLines(line - 1, line - 1);
    }

    function menuLineNumber(e: React.MouseEvent) {
        e.preventDefault();
        const line = parseInt((e.target as HTMLElement).getAttribute("line") || "0");
        termServer.current?.settingZeroLine(line);
    }

    useEffect(() => {
        termServer.current?.settingConfig(termConfig);
    }, [termConfig]);

    useEffect(() => {
        let disposed = false;
        const closeFuns: Array<() => void> = [];

        async function init() {
            const host = divRef.current;
            if (!host) return;
            const { default: TermServerClass } = await import("@/components/ssh/term_server");
            if (disposed) return;
            const instance = new TermServerClass({ server });
            termServer.current = instance;
            closeFuns.push(() => instance.close());
            server.snapshotFn.termData = () => {
                return {
                    termData: instance.snapshot(),
                    webData: {
                        searchData: searchDataRef.current,
                        selectPrompt: selectPromptRef.current,
                        searchIsFocus: searchIsFocusRef.current,
                    },
                } satisfies { termData: TerminalSnapshot; webData: { searchData: SearchData; selectPrompt: typeof selectPrompt; searchIsFocus: boolean } };
            };
            instance.settingConfig(termConfig);
            const snapshot = server.snapshot.termData as { termData: TerminalSnapshot; webData?: { searchData?: SearchData; selectPrompt?: typeof selectPrompt; searchIsFocus?: boolean } } | undefined;
            if (snapshot) {
                delete server.snapshot.termData;
                instance.snapshotReset(snapshot.termData, host);
                if (snapshot.webData?.selectPrompt) setSelectPromptSync(snapshot.webData.selectPrompt);
                if (snapshot.webData?.searchData) {
                    setSearchDataSync(snapshot.webData.searchData);
                    if (snapshot.webData.searchData.text) {
                        clickSearch(true, snapshot.webData.searchData);
                        setSearchDataSync(snapshot.webData.searchData);
                    }
                }
                if (snapshot.webData?.searchIsFocus) {
                    setSearchFocusSync(true);
                    focusSearchInput();
                }
            } else {
                instance.initTerminal(host);
            }
            await instance.connect(!snapshot);
            if (!snapshot) {
                server.server.lastConnectAt = Date.now();
                await useServerDataStore.getState().serverDataChange(server.server);
            }
            instance.onLineNumberChange(updateLineNumbers);
            instance.onKeyEvent(termKeydown);
            instance.onSelectionChange((text) => {
                selectedText.current = text;
                const show = Boolean(text);
                setSelectPromptSync({
                    show: show && Boolean(mousePos.current.x),
                    x: mousePos.current.x,
                    y: mousePos.current.y,
                    text,
                });
            });
            instance.onCwdChange((path) => {
                emit(DirectRemotePathEventKey, { sid: server.sessionId, path });
            });
            instance.onData((command) => {
                // 融合终端中，当前终端的输入通过总线广播到同组其他终端。
                if (!groupId) return;
                emit(TermGroupCommandEventKey, { groupId, command, sessionId: server.sessionId });
            });
            instance.onSearchChange((count, index) => {
                setSearchDataSync((prev) => ({ ...prev, count, index: index + 1 }));
            });
            closeFuns.push(
                on(TermGroupCommandEventKey, (event) => {
                    if (event.groupId !== groupId) return;
                    if (event.sessionId === server.sessionId) return;
                    void instance.write(event.command);
                }),
            );
            const unregister = registerKeyEvent((event) => termKeydown(event as unknown as KeyboardEvent));
            closeFuns.push(unregister);
            setReady(true);
        }

        void init().catch((err) => {
            console.error("init terminal error:", err);
            showToast("终端初始化失败", "error");
        });

        return () => {
            disposed = true;
            closeFuns.forEach((close) => close());
            termServer.current = null;
        };
        // 终端实例与 SSH 会话一一对应，配置变化由单独 effect 下发，避免重建连接。
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [server.sessionId]);

    useEffect(() => {
        const rootEl = root.current;
        const termEl = divRef.current;
        if (!rootEl || !termEl) return;
        let gestureScale = 1;
        const onGestureStart = (e: WebKitGestureEvent) => {
            e.preventDefault();
            gestureScale = e.scale ?? 1;
        };
        const onGestureChange = (e: WebKitGestureEvent) => {
            e.preventDefault();
            const scale = e.scale ?? gestureScale;
            // macOS WebKit 的 gesture 事件是增量缩放；按 Vue 版逻辑转成字体大小变化。
            termChangeFontSize(10 * (scale - gestureScale));
            gestureScale = scale;
        };
        const onMouseUp = (e: MouseEvent) => {
            if (eventHave(e, termEl)) {
                mousePos.current = { x: e.clientX, y: e.clientY };
            } else {
                mousePos.current = { x: 0, y: 0 };
            }
        };
        const onContextMenu = (e: MouseEvent) => openContextMenu(e);
        rootEl.addEventListener("gesturestart", onGestureStart);
        rootEl.addEventListener("gesturechange", onGestureChange);
        rootEl.addEventListener("mouseup", onMouseUp);
        termEl.addEventListener("contextmenu", onContextMenu);
        return () => {
            rootEl.removeEventListener("gesturestart", onGestureStart);
            rootEl.removeEventListener("gesturechange", onGestureChange);
            rootEl.removeEventListener("mouseup", onMouseUp);
            termEl.removeEventListener("contextmenu", onContextMenu);
        };
        // Vue 版在 onMounted 中只注册一次 DOM 事件；回调内部通过 refs 读取最新搜索/选中状态。
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return (
        <div ref={panelRoot} className="Term relative flex h-full w-full min-h-0 flex-col overflow-hidden">
            <div style={{ display: showTermPanel || groupId ? undefined : "none" }} className="relative viwer root term-module min-h-0 flex-1 overflow-hidden" ref={root}>
                {!groupId || groupActive ? <div ref={lineNumber} className="line-number" onClick={selectLine} onContextMenu={menuLineNumber} /> : null}
                <div className="term" ref={divRef} />
                <div style={{ display: searchData.show ? undefined : "none" }} className="search">
                    <div className="grow flex justify-between items-center ml-2 left">
                        <Icon icon="si:search-alt-fill" className="mr-1" />
                        {/* 搜索内容需要严格保留用户输入的大小写，避免 macOS/WebKit 按自然语言自动改写。 */}
                        <SystemInput
                            ref={searchInput}
                            value={searchData.text}
                            className="grow w-full"
                            onChange={(value) => updateSearch({ text: value })}
                            onFocus={() => setSearchFocusSync(true)}
                            onBlur={() => setSearchFocusSync(false)}
                        />
                        <Icon
                            icon="mdi:format-lowercase"
                            className={`pointer icon${searchData.caseSensitive ? " active" : ""}`}
                            onClick={() => updateSearch({ caseSensitive: !searchData.caseSensitive })}
                        />
                        <Icon icon="icon-park-solid:word" className={`pointer icon${searchData.wholeWord ? " active" : ""}`} onClick={() => updateSearch({ wholeWord: !searchData.wholeWord })} />
                        <Icon icon="mdi:regex" className={`pointer icon${searchData.regex ? " active" : ""}`} onClick={() => updateSearch({ regex: !searchData.regex })} />
                        <p className="cnt">{searchData.count ? `${searchData.index}/${searchData.count}` : "0"}</p>
                    </div>
                    <div className="flex justify-center items-center">
                        <Icon icon="si:expand-less-fill" className="pointer icon" onClick={() => clickSearch(false)} />
                        <Icon icon="si:expand-more-fill" className="pointer icon" onClick={() => clickSearch(true)} />
                        <Icon icon="si:close-duotone" className="pointer icon" onClick={hideSearch} />
                    </div>
                </div>
                {selectPrompt.show ? (
                    <div className="select-prompt flex" style={{ left: `${selectPrompt.x}px`, top: `${selectPrompt.y + 10}px` }}>
                        <Icon
                            icon="si:copy-alt-duotone"
                            className="pointer icon"
                            onClick={(event) => {
                                event.stopPropagation();
                                clickCopyText();
                            }}
                        />
                        <Icon
                            icon="si:copy-fill"
                            className="pointer icon"
                            onClick={(event) => {
                                event.stopPropagation();
                                applyText();
                            }}
                        />
                        <Icon
                            icon="si:search-alt-fill"
                            className="pointer icon"
                            onClick={(event) => {
                                event.stopPropagation();
                                applySearch();
                            }}
                        />
                    </div>
                ) : null}
            </div>
            {ready && !groupId ? (
                <>
                    <div style={{ display: showSftpPanel && showTermPanel ? undefined : "none" }}>
                        <LayoutRowResizer
                            container={panelRoot}
                            modelValue={sftpPanelHeightPx}
                            // Vue 版拖拽时直接 v-model 到 Pinia ref，不触发配置保存事件。
                            onChange={(value) => useConfigStore.setState({ sftpPanelHeightPx: value })}
                        />
                    </div>
                    <div
                        style={
                            showTermPanel
                                ? {
                                      display: showSftpPanel ? undefined : "none",
                                      height: `${sftpPanelHeightPx}px`,
                                  }
                                : { display: showSftpPanel ? undefined : "none" }
                        }
                        className={!showTermPanel ? "overflow-hidden min-h-0 flex-1" : "overflow-hidden"}
                    >
                        <Sftp className="h-full min-h-0" server={server} writeTerminal={writeToTerm} />
                    </div>
                </>
            ) : null}
        </div>
    );
}
