// src/components/ssh/Channels.vue
<script setup lang="ts">
const channelInstancesStore = useChannelInstancesStore();

const instances = computed(() => channelInstancesStore.instances);
const selectSessionId = computed(() => channelInstancesStore.selectSessionId);

onMounted(async () => {});
</script>

<template>
    <div class="w-full h-full relative">
        <div v-for="(server, i) in instances" :key="i" class="channel" :style="{ zIndex: server.zindex }" :class="{ active: selectSessionId === server.sessionId }">
            <slot :server="server" />
        </div>
    </div>
</template>

<style scoped lang="scss">
.channel {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    opacity: 0;

    &.active {
        pointer-events: auto;
        opacity: 1;
    }
}
</style>

// web-next/src/components/ssh/Channels/index.tsx
"use client";

import { useChannelInstancesStore, type ChannelData } from "@/stores/channelInstances";
import "./index.scss";

export type ChannelsProps = {
    children: (server: ChannelData) => React.ReactNode;
};

export default function Channels({ children }: ChannelsProps) {
    const instances = useChannelInstancesStore((state) => state.instances);
    const selectSessionId = useChannelInstancesStore((state) => state.selectSessionId);

    return (
        <div className="Channels w-full h-full relative">
            {instances.map((server) => (
                <div key={server.sessionId} className={`channel${selectSessionId === server.sessionId ? " active" : ""}`} style={{ zIndex: server.zindex }}>
                    {children(server)}
                </div>
            ))}
        </div>
    );
}
