// src/components/ssh/ServerResource.vue
<script setup lang="ts">
const serverOverviewStore = useServerOverviewStore();
const channelInstancesStore = useChannelInstancesStore();
const { selectSession, selectSessionId } = toRefs(channelInstancesStore);
const overview = computed<ServerOverviewState | undefined>(() => selectSession.value?.overview);
const processes = computed(() => overview.value?.processes ?? []);
const procSort = computed<OverviewProcessSort>(() => (overview.value?.processSort === "cpu" ? "cpu" : "mem"));

function setProcSort(v: OverviewProcessSort) {
    const o = selectSession.value?.overview;
    if (o) o.processSort = v === "cpu" ? "cpu" : "mem";
}
/** 折线图按“本机视角”显示，需与 localNetUp/localNetDown 保持一致。 */
const netUpSeries = computed(() => overview.value?.netUpSeries ?? []);
const netDownSeries = computed(() => overview.value?.netDownSeries ?? []);
/**
 * 仅用最近若干点定纵轴，避免缓冲里左侧仍保留的旧尖峰把后续低流量压扁在底部。
 * 与 serverOverview 中 NET_SERIES_POINTS（12）配套：取尾部约一半窗口。
 */
const CHART_Y_AXIS_TAIL = 6;

function chartYTailMax(values: number[]): number {
    const n = values.length;
    if (n === 0) return 1;
    const tail = Math.min(n, CHART_Y_AXIS_TAIL);
    const slice = tail >= n ? values : values.slice(-tail);
    return Math.max(1, ...slice);
}
/** store 中的 netUp/netDown 是远端网卡 TX/RX；面板按“本机”视角展示上传/下载。 */
const localNetUp = computed(() => overview.value?.netUp ?? "");
const localNetDown = computed(() => overview.value?.netDown ?? "");
const latency = computed(() => overview.value?.latency ?? "");
const ifaceOptions = computed(() => {
    const o = overview.value;
    if (!o) return [];
    if (o.ifaceOptions.length) return o.ifaceOptions;
    return o.iface ? [o.iface] : ["—"];
});

/** 与 store.overview.iface 同步，保证图表/上下行速率与 net_by_iface 一致 */
const ifaceModel = computed({
    get: () => overview.value?.iface ?? "",
    set: (v: string) => {
        const id = selectSessionId.value;
        if (id) serverOverviewStore.setOverviewIface(id, v);
    },
});

/** 网速序列单位为 KiB/s（与 channelInstances 一致） */
const KiB = 1024;
const MiB = KiB * KiB;

const chartYScaleSource = computed(() => Math.max(chartYTailMax(netUpSeries.value), chartYTailMax(netDownSeries.value)));

const netChartScale = computed(() => {
    const maxRaw = Math.max(chartYScaleSource.value, 1);
    if (maxRaw >= MiB) return { divisor: MiB, suffix: "G" };
    if (maxRaw >= KiB) return { divisor: KiB, suffix: "M" };
    return { divisor: 1, suffix: "K" };
});

/** 与左侧刻度顶对齐的绘图上限（nice number），曲线按此值归一化 */
const chartPlotMax = computed(() => {
    const maxRaw = chartYScaleSource.value;
    const { divisor } = netChartScale.value;
    return netTickTop(maxRaw / divisor) * divisor;
});

function netTickTop(scaledMax: number) {
    const sm = scaledMax <= 0 || !Number.isFinite(scaledMax) ? 1 : scaledMax;
    const x = sm * 1.05;
    const pow = Math.floor(Math.log10(x));
    const base = 10 ** pow;
    const m = x / base;
    const niceM = m <= 1 ? 1 : m <= 2 ? 2 : m <= 5 ? 5 : 10;
    let hi = niceM * base;
    if (hi < sm) hi *= 10;
    return hi;
}

function fmtNetTick(v: number) {
    if (!Number.isFinite(v)) return "0";
    const a = Math.abs(v);
    if (a >= 100) return String(Math.round(v));
    if (a >= 10) return Math.abs(v - Math.round(v)) < 0.06 ? String(Math.round(v)) : v.toFixed(1);
    return Math.abs(v - Math.round(v)) < 0.06 ? String(Math.round(v)) : v.toFixed(2);
}

function buildChartPoints(series: number[]) {
    const s = series;
    const n = s.length;
    const w = 100;
    const h = 40;
    const max = Math.max(chartPlotMax.value, 1);
    if (n < 2) {
        const y = h - ((s[0] ?? 0) / max) * h;
        return [
            { x: 0, y },
            { x: w, y },
        ];
    }
    return s.map((v, i) => {
        const x = (i / (n - 1)) * w;
        const y = h - (v / max) * h;
        return { x, y };
    });
}

function buildChartLinePath(points: Array<{ x: number; y: number }>) {
    if (!points.length) return "";
    return points.map((p, i) => `${i === 0 ? "M" : "L"} ${p.x} ${p.y}`).join(" ");
}

const chartUpPath = computed(() => {
    const pts = buildChartPoints(netUpSeries.value);
    return buildChartLinePath(pts);
});

const chartDownPath = computed(() => {
    const pts = buildChartPoints(netDownSeries.value);
    return buildChartLinePath(pts);
});

const chartGridPath = computed(() => {
    return "M 0 0 L 100 0 M 0 13.33 L 100 13.33 M 0 26.66 L 100 26.66 M 0 40 L 100 40";
});

const chartTicks = computed(() => {
    const pm = chartPlotMax.value;
    const { divisor, suffix } = netChartScale.value;
    const hi = pm / divisor;
    const t2 = (hi * 2) / 3;
    const t3 = hi / 3;
    return [hi, t2, t3].map((v) => `${fmtNetTick(v)}${suffix}`);
});
</script>

<template>
    <div class="module resource">
        <div class="proc-toolbar">
            <span class="proc-toolbar-label">进程 TOP5</span>
            <span class="proc-toolbar-hint">点击「内存 / CPU」表头按该项降序</span>
        </div>
        <table class="tbl proc">
            <colgroup>
                <col class="col-mem" />
                <col class="col-cpu" />
                <col class="col-cmd" />
            </colgroup>
            <thead>
                <tr>
                    <th scope="col" class="proc-th-sort" :class="{ 'proc-th-sort--active': procSort === 'mem' }" :aria-sort="procSort === 'mem' ? 'descending' : 'none'">
                        <button type="button" class="proc-sort-btn" @click="setProcSort('mem')">
                            <span class="proc-sort-label">内存</span>
                            <span v-if="procSort === 'mem'" class="proc-sort-mark" title="当前按内存降序">↓</span>
                        </button>
                    </th>
                    <th scope="col" class="proc-th-sort" :class="{ 'proc-th-sort--active': procSort === 'cpu' }" :aria-sort="procSort === 'cpu' ? 'descending' : 'none'">
                        <button type="button" class="proc-sort-btn" @click="setProcSort('cpu')">
                            <span class="proc-sort-label">CPU</span>
                            <span v-if="procSort === 'cpu'" class="proc-sort-mark" title="当前按 CPU 降序">↓</span>
                        </button>
                    </th>
                    <th scope="col" class="proc-th-plain">命令</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(p, i) in processes" :key="i" :class="{ alt: i % 2 === 1 }">
                    <td>{{ p.mem }}</td>
                    <td>{{ p.cpu }}</td>
                    <td class="cmd">{{ p.cmd }}</td>
                </tr>
            </tbody>
        </table>

        <div class="net-toolbar">
            <span class="net-up">↑ {{ localNetUp }}</span>
            <span class="net-down">↓ {{ localNetDown }}</span>
            <select v-model="ifaceModel" class="iface-select">
                <option v-for="o in ifaceOptions" :key="o" :value="o">{{ o }}</option>
            </select>
        </div>
        <div class="chart-wrap">
            <div class="chart-y">
                <span v-for="t in chartTicks" :key="t">{{ t }}</span>
            </div>
            <svg class="chart" viewBox="0 0 100 40" preserveAspectRatio="none" overflow="hidden">
                <path class="chart-grid" :d="chartGridPath" />
                <path class="chart-line chart-line-down" :d="chartDownPath" />
                <path class="chart-line chart-line-up" :d="chartUpPath" />
            </svg>
        </div>
        <div class="net-footer">
            <span>{{ latency }}</span>
            <span>本机</span>
        </div>
    </div>
</template>

<style scoped lang="scss">
.resource {
    padding: 10px 12px;
    line-height: 1.35;
    border-radius: 8px;
}

.proc-toolbar {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 8px;
    flex-wrap: wrap;
}

.proc-toolbar-label {
    font-size: var(--font-size-xs);
    font-weight: 600;
    opacity: 0.9;
}

.proc-toolbar-hint {
    margin-left: auto;
    font-size: var(--font-size-2xs);
    opacity: 0.65;
}

.proc-th-sort {
    padding: 0;
    vertical-align: bottom;
}

.proc-th-sort--active .proc-sort-label {
    font-weight: 700;
}

.proc-sort-btn {
    display: inline-flex;
    align-items: center;
    gap: 3px;
    width: 100%;
    margin: 0;
    padding: 5px 6px;
    border: none;
    background: transparent;
    font: inherit;
    color: inherit;
    text-align: left;
    cursor: pointer;
    border-radius: 4px;
    line-height: 1.2;
}

.proc-sort-mark {
    font-size: var(--font-size-2xs);
    opacity: 0.95;
    font-weight: 700;
}

.proc-th-plain {
    font-weight: 600;
    padding: 5px 6px;
    text-align: left;
    font-size: var(--font-size-xs);
}

.tbl {
    width: 100%;
    border-collapse: collapse;
    margin: 0 0 10px;
    table-layout: fixed;
}

.tbl.proc col.col-mem {
    width: 6em;
}

.tbl.proc col.col-cpu {
    width: 5em;
}

.tbl.proc col.col-cmd {
    width: auto;
}

.tbl.proc th:not(.proc-th-sort):not(.proc-th-plain) {
    font-weight: 600;
    padding: 5px 6px;
    text-align: left;
    font-size: var(--font-size-xs);
}

.tbl.proc th:nth-child(1),
.tbl.proc th:nth-child(2),
.tbl.proc td:nth-child(1),
.tbl.proc td:nth-child(2) {
    white-space: nowrap;
    padding-left: 4px;
    padding-right: 4px;
}

.tbl.proc td {
    padding: 4px 6px;
    font-size: var(--font-size-xs);
}

.tbl.proc .cmd {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.net-toolbar {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
}

.net-up {
    font-weight: 600;
}

.net-down {
    font-weight: 600;
}

.iface-select {
    margin-left: auto;
    font-size: var(--font-size-xs);
    padding: 4px 8px;
    border-radius: 6px;
    max-width: 130px;
    border: none;
    outline: none;
    cursor: pointer;
}

.chart-wrap {
    display: flex;
    margin-top: 8px;
    gap: 6px;
    height: 72px;
}

.chart-y {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    font-size: var(--font-size-2xs);
    text-align: right;
    min-width: 3.2em;
    flex-shrink: 0;
    padding: 2px 0;
}

.chart {
    flex: 1;
    width: 100%;
    height: 100%;
    min-height: 64px;
}

.chart-grid {
    fill: none;
    stroke-width: 0.28;
    opacity: 0.45;
}

.chart-line {
    fill: none;
    stroke-width: 1;
    stroke-linecap: round;
    stroke-linejoin: round;
}

.net-footer {
    display: flex;
    justify-content: space-between;
    font-size: var(--font-size-xs);
    margin-top: 6px;
    padding: 0 2px;
}
</style>

// web-next/src/components/ssh/ServerResource/index.tsx
"use client";

import { useChannelInstancesStore, isChannelInstance } from "@/stores/channelInstances";
import { useServerOverviewStore, type OverviewProcessSort } from "@/stores/serverOverview";
import "./index.scss";

export default function ServerResource() {
    const instances = useChannelInstancesStore((state) => state.instances);
    const selectSessionId = useChannelInstancesStore((state) => state.selectSessionId);
    const selectSession = instances.find((item) => item.sessionId === selectSessionId);
    const instance = selectSession && isChannelInstance(selectSession) ? selectSession : null;
    const overview = instance?.overview;
    const processes = overview?.processes ?? [];
    const procSort: OverviewProcessSort = overview?.processSort === "cpu" ? "cpu" : "mem";
    const ifaceOptions = overview?.ifaceOptions.length ? overview.ifaceOptions : overview?.iface ? [overview.iface] : ["—"];
    const chartScaleSource = Math.max(chartYTailMax(overview?.netUpSeries ?? []), chartYTailMax(overview?.netDownSeries ?? []));
    const chartScale = netChartScale(chartScaleSource);
    const chartPlotMax = netTickTop(chartScaleSource / chartScale.divisor) * chartScale.divisor;
    const chartTicks = [chartPlotMax / chartScale.divisor, (chartPlotMax / chartScale.divisor) * (2 / 3), (chartPlotMax / chartScale.divisor) / 3].map((value) => `${fmtNetTick(value)}${chartScale.suffix}`);

    const chartUpPath = buildChartPath(overview?.netUpSeries ?? [], chartPlotMax);
    const chartDownPath = buildChartPath(overview?.netDownSeries ?? [], chartPlotMax);

    function setProcSort(v: OverviewProcessSort) {
        if (instance?.sessionId) void useServerOverviewStore.getState().setOverviewProcessSort(instance.sessionId, v);
    }

    function setIface(v: string) {
        if (instance?.sessionId) void useServerOverviewStore.getState().setOverviewIface(instance.sessionId, v);
    }

    return (
        <div className="ServerResource module resource">
            <div className="proc-toolbar">
                <span className="proc-toolbar-label">进程 TOP5</span>
                <span className="proc-toolbar-hint">点击「内存 / CPU」表头按该项降序</span>
            </div>
            <table className="tbl proc">
                <colgroup>
                    <col className="col-mem" />
                    <col className="col-cpu" />
                    <col className="col-cmd" />
                </colgroup>
                <thead>
                    <tr>
                        <th scope="col" className={`proc-th-sort${procSort === "mem" ? " proc-th-sort--active" : ""}`} aria-sort={procSort === "mem" ? "descending" : "none"}>
                            <button type="button" className="proc-sort-btn" onClick={() => setProcSort("mem")}>
                                <span className="proc-sort-label">内存</span>
                                {procSort === "mem" ? (
                                    <span className="proc-sort-mark" title="当前按内存降序">
                                        ↓
                                    </span>
                                ) : null}
                            </button>
                        </th>
                        <th scope="col" className={`proc-th-sort${procSort === "cpu" ? " proc-th-sort--active" : ""}`} aria-sort={procSort === "cpu" ? "descending" : "none"}>
                            <button type="button" className="proc-sort-btn" onClick={() => setProcSort("cpu")}>
                                <span className="proc-sort-label">CPU</span>
                                {procSort === "cpu" ? (
                                    <span className="proc-sort-mark" title="当前按 CPU 降序">
                                        ↓
                                    </span>
                                ) : null}
                            </button>
                        </th>
                        <th scope="col" className="proc-th-plain">
                            命令
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {processes.map((p, i) => (
                        <tr key={i} className={i % 2 === 1 ? "alt" : ""}>
                            <td>{p.mem}</td>
                            <td>{p.cpu}</td>
                            <td className="cmd">{p.cmd}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <div className="net-toolbar">
                <span className="net-up">↑ {overview?.netUp ?? ""}</span>
                <span className="net-down">↓ {overview?.netDown ?? ""}</span>
                <select value={overview?.iface ?? ""} className="iface-select" onChange={(event) => setIface(event.target.value)}>
                    {ifaceOptions.map((o) => (
                        <option key={o} value={o}>
                            {o}
                        </option>
                    ))}
                </select>
            </div>
            <div className="chart-wrap">
                <div className="chart-y">
                    {chartTicks.map((tick) => (
                        <span key={tick}>{tick}</span>
                    ))}
                </div>
                <svg className="chart" viewBox="0 0 100 40" preserveAspectRatio="none" overflow="hidden">
                    <path className="chart-grid" d="M 0 0 L 100 0 M 0 13.33 L 100 13.33 M 0 26.66 L 100 26.66 M 0 40 L 100 40" />
                    <path className="chart-line chart-line-down" d={chartDownPath} />
                    <path className="chart-line chart-line-up" d={chartUpPath} />
                </svg>
            </div>
            <div className="net-footer">
                <span>{overview?.latency ?? ""}</span>
                <span>本机</span>
            </div>
        </div>
    );
}

const CHART_Y_AXIS_TAIL = 6;
const KiB = 1024;
const MiB = KiB * KiB;

function chartYTailMax(values: number[]): number {
    const n = values.length;
    if (n === 0) return 1;
    const tail = Math.min(n, CHART_Y_AXIS_TAIL);
    const slice = tail >= n ? values : values.slice(-tail);
    return Math.max(1, ...slice);
}

function netChartScale(maxRaw: number) {
    if (maxRaw >= MiB) return { divisor: MiB, suffix: "G" };
    if (maxRaw >= KiB) return { divisor: KiB, suffix: "M" };
    return { divisor: 1, suffix: "K" };
}

function netTickTop(scaledMax: number) {
    const sm = scaledMax <= 0 || !Number.isFinite(scaledMax) ? 1 : scaledMax;
    const x = sm * 1.05;
    const pow = Math.floor(Math.log10(x));
    const base = 10 ** pow;
    const m = x / base;
    const niceM = m <= 1 ? 1 : m <= 2 ? 2 : m <= 5 ? 5 : 10;
    let hi = niceM * base;
    if (hi < sm) hi *= 10;
    return hi;
}

function fmtNetTick(v: number) {
    if (!Number.isFinite(v)) return "0";
    const a = Math.abs(v);
    if (a >= 100) return String(Math.round(v));
    if (a >= 10) return Math.abs(v - Math.round(v)) < 0.06 ? String(Math.round(v)) : v.toFixed(1);
    return Math.abs(v - Math.round(v)) < 0.06 ? String(Math.round(v)) : v.toFixed(2);
}

function buildChartPath(series: number[], chartPlotMax: number) {
    const n = series.length;
    const w = 100;
    const h = 40;
    // 纵轴按最近窗口的 nice tick 归一化，避免历史尖峰长期压扁当前曲线。
    const max = Math.max(chartPlotMax, 1);
    if (n < 2) {
        const y = h - ((series[0] ?? 0) / max) * h;
        return `M 0 ${y} L ${w} ${y}`;
    }
    return series.map((v, i) => `${i === 0 ? "M" : "L"} ${(i / (n - 1)) * w} ${h - (v / max) * h}`).join(" ");
}
