// web-next/src/components/ssh/ServerDisk/index.tsx
"use client";

import { useEffect, useState } from "react";
import { useChannelInstancesStore, isChannelInstance } from "@/stores/channelInstances";
import useBus, { ActiveFileEventKey, DirectRemotePathEventKey } from "@/hooks/useBus";
import "./index.scss";

export default function ServerDisk() {
    const selectSession = useChannelInstancesStore((state) => state.selectSession);
    const instance = selectSession && isChannelInstance(selectSession) ? selectSession : null;
    const [activePath, setActivePath] = useState("/");
    const { emit, on } = useBus();
    const overview = instance?.overview;
    const disks = overview?.disks ?? [];
    const activeDisk =
        activePath === "/"
            ? disks.find((d) => d.path === "/")
            : disks.filter((d) => activePath.startsWith(d.path)).sort((a, b) => b.path.length - a.path.length)[0];

    function onActiveDisk(path: string) {
        setActivePath(path);
        if (instance) emit(DirectRemotePathEventKey, { sid: instance.sessionId, path });
    }

    useEffect(() => {
        return on(ActiveFileEventKey, (event) => {
            if (event.sid !== instance?.sessionId) return;
            setActivePath(event.path);
        });
    }, [instance?.sessionId, on]);

    return (
        <div className="ServerDisk module disk">
            <table className="tbl disk">
                <thead>
                    <tr>
                        <th>路径</th>
                        <th>可用/大小</th>
                    </tr>
                </thead>
                <tbody>
                    {disks.map((d, i) => (
                        <tr key={i} className={d === activeDisk ? "root" : ""} onClick={() => onActiveDisk(d.path)}>
                            <td className="path">{d.path}</td>
                            <td className="disk-cell">
                                <div className="disk-bar" style={{ width: `${d.pct}%` }} />
                                <span className="disk-txt">
                                    {d.avail}/{d.size}
                                </span>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}

// src/components/ssh/ServerDisk.vue
<script setup lang="ts">
import { ActiveFileEventKey, DirectRemotePathEventKey, useBus } from "@/composables/useBus";

const { selectSession } = useChannelInstancesStore();
const { emit, on, off } = useBus();

const overview = computed(() => selectSession?.overview);

const activePath = ref("/");

const activeDisk = computed(() => {
    const disks = overview.value?.disks;
    if (!disks) return undefined;
    if (activePath.value === "/") {
        return disks.find((d) => d.path === "/");
    }
    const matchDisks = disks.filter((d) => activePath.value.startsWith(d.path));
    return matchDisks.sort((a, b) => b.path.length - a.path.length)[0];
});

function onActiveDisk(path: string) {
    activePath.value = path;
    emit(DirectRemotePathEventKey, { sid: selectSession!.sessionId, path: activePath.value });
}

onMounted(() => {
    on(ActiveFileEventKey, (event) => {
        if (event.sid !== selectSession?.sessionId) return;
        activePath.value = event.path;
    });
});

onUnmounted(() => {
    off(ActiveFileEventKey);
});
</script>

<template>
    <div class="module disk">
        <table class="tbl disk">
            <thead>
                <tr>
                    <th>路径</th>
                    <th>可用/大小</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(d, i) in overview?.disks" :key="i" :class="{ root: d === activeDisk }" @click="onActiveDisk(d.path)">
                    <td class="path">{{ d.path }}</td>
                    <td class="disk-cell">
                        <div class="disk-bar" :style="{ width: d.pct + '%' }" />
                        <span class="disk-txt">{{ d.avail }}/{{ d.size }}</span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<style scoped lang="scss">
.disk {
    padding: 10px 12px;
    line-height: 1.35;
    border-radius: 8px;
}

.tbl {
    width: 100%;
    border-collapse: collapse;
    margin: 0;
    table-layout: fixed;
}

.tbl.disk thead {
}

.tbl.disk th {
    font-weight: 600;
    padding: 5px 6px;
    text-align: left;
    font-size: var(--font-size-xs);
}

.tbl.disk td {
    padding: 5px 6px;
    font-size: var(--font-size-xs);
    border-bottom: 1px solid rgba(0, 0, 0, 0.2);
    vertical-align: middle;
}

.tbl.disk .path {
    word-break: break-all;
}

.disk-cell {
    position: relative;
    min-width: 88px;
}

.disk-bar {
    position: absolute;
    left: 0;
    top: 3px;
    bottom: 3px;
    max-width: calc(100% - 4px);
    border-radius: 4px;
    pointer-events: none;
}

.disk-txt {
    position: relative;
    z-index: 1;
    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
}
</style>
