// src/components/window/MainWin.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
const channelInstancesStore = useChannelInstancesStore();
const appStore = useAppStore();
const { isMainWin } = storeToRefs(appStore);

const { instances } = storeToRefs(channelInstancesStore);
</script>

<template>
    <DefaultLayout v-if="instances.length || !isMainWin" />
    <ServerList v-else />
</template>

<style scoped lang="scss"></style>

// web-next/src/components/window/MainWin/index.tsx
"use client";

import "./index.scss";
import ServerList from "@/components/ServerList";
import DefaultLayout from "@/layout/DefaultLayout";
import { useAppStore } from "@/stores/app";
import { useChannelInstancesStore } from "@/stores/channelInstances";

export default function MainWin() {
    const instances = useChannelInstancesStore((state) => state.instances);
    const isMainWin = useAppStore((state) => state.isMainWin);

    return <main className="MainWin">{instances.length || !isMainWin ? <DefaultLayout /> : <ServerList />}</main>;
}
